<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PaginaEjemplo3.aspx.cs" Inherits="WebApplication1.Web_Forms.PaginaEjemplo3" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
       <h3>Nombre</h3>
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        <br />
        <h3>Año</h3>
        <asp:TextBox ID="TextBox1_1" runat="server"></asp:TextBox>
        <br />
        <h3>Genero</h3>
        <asp:DropDownList ID="DropDownListGenero" runat="server"></asp:DropDownList>
        <br />
        <h3>Director</h3>
        <asp:DropDownList ID="DropDownListDirector" runat="server"></asp:DropDownList>
        <br />
         <h3>Cantidad</h3>
        <asp:TextBox ID="TextBox1_2" runat="server"></asp:TextBox>
        <br />
        <asp:Button ID="Button1" runat="server" Text="Agregar" OnClick="Button1_Click" />
        <br />
        <asp:Label ID="LabelDirector1Vacio" runat="server" Text=""></asp:Label>
        <br />
        <h3>Elija una pelicula para ver su informacion</h3>
        <br />
        <asp:DropDownList ID="DropDownList1" runat="server" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" AutoPostBack="true"></asp:DropDownList>
        <br />
        <asp:Label ID="Label1" runat="server" Text=""></asp:Label>
        <br />
        <h3>Eliminar director</h3>
        <br />
        <asp:Button ID="Button2" runat="server" Text="Borrar genero elegido (1)" OnClick="Button2_Click" />
        <br />
        <asp:Button ID="Button2_1" runat="server" Text="Borrar genero elegido (2)" OnClick="Button2_1_Click" />
        <br />
        <h3>Ingrese un nuevo Nombre de la pelicula</h3>
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
        <br />
        <h3>Ingrese un nuevo año para la pelicula</h3>
        <asp:TextBox ID="TextBox2_1" runat="server"></asp:TextBox>
        <br />
        <h3>Elija un nuevo genero para la pelicula</h3>
        <asp:DropDownList ID="DropDownList2" runat="server"></asp:DropDownList>
        <br />
        <h3>Elija un nuevo director para la pelicula</h3>
        <asp:DropDownList ID="DropDownList2_1" runat="server"></asp:DropDownList>
        <br />
        <h3>Ingrese la nueva cantidad para la pelicula</h3>
        <asp:TextBox ID="TextBox2_2" runat="server"></asp:TextBox>
        <br />
        <asp:Button ID="Button3" runat="server" Text="Modificar pelicula elegida (1)" OnClick="Button3_Click" />
        <br />
        <asp:Button ID="Button3_1" runat="server" Text="Modificar pelicula elegida (2)" OnClick="Button3_1_Click" />
        <br />
        <asp:Label ID="LabelGeneroVacio2" runat="server" Text=""></asp:Label>
        <br />
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" ></asp:GridView>

    </div>
    </form>
</body>
</html>
