//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Año { get; set; }
        public int Genero { get; set; }
        public int Director { get; set; }
        public bool Disponibilidad { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Director Director1 { get; set; }
        public virtual Genero Genero1 { get; set; }
    }
}
